# Generated by Django 2.1 on 2018-09-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='rating',
        ),
        migrations.AddField(
            model_name='card',
            name='current_rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='next_turn_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='no_of_turns_to_be_skipped',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='previous_rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='quiz_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='no_of_cards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
